name: Run tests

on:
  push:
    branches:
      - specmatic_node_git 

jobs:
    test:
        strategy:
          matrix:
            node-version: [20.x]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v4
          
          - name: Set up JRE 17
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '17'
              java-package: 'jre'
              
          - name: Set up Node
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}
          
          - name: Run npm install
            run: npm install
          
          - name: Run npm test
            run: npm run test-ci
